### ISSUE TITLE
SDK Sample App crashes on Android 2.3.x

### ISSUE THREAD

**Issue by matthiaswenz** [Microsoft/ApplicationInsights-Android#47]
After testing a fix to #46 in a feature branch, this exception occurs on all Android 2.3.x devices for me:

```
06-08 17:37:08.046  13194-13194/com.microsoft.applicationinsights.sampleapp E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NullPointerException
            at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:355)
            at android.widget.ArrayAdapter.getView(ArrayAdapter.java:323)
            at android.widget.AbsListView.obtainView(AbsListView.java:2096)
            at android.widget.ListView.makeAndAddView(ListView.java:1752)
            at android.widget.ListView.fillDown(ListView.java:677)
            at android.widget.ListView.fillFromTop(ListView.java:734)
            at android.widget.ListView.layoutChildren(ListView.java:1605)
            at android.widget.AbsListView.onLayout(AbsListView.java:1925)
            at android.view.View.layout(View.java:7446)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
            at android.view.View.layout(View.java:7446)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
            at android.view.View.layout(View.java:7446)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
            at android.view.View.layout(View.java:7446)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
            at android.view.View.layout(View.java:7446)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
            at android.view.View.layout(View.java:7446)
            at android.view.ViewRoot.performTraversals(ViewRoot.java:1140)
            at android.view.ViewRoot.handleMessage(ViewRoot.java:1859)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:3694)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
            at dalvik.system.NativeStart.main(Native Method)
```

Seems related to the setup of the list adapter in [ItemListFragment.java](https://github.com/Microsoft/ApplicationInsights-Android/blob/b8e42d23de3cc6c7587d33ef13baa258350f3fdb/app-sample/src/main/java/com/microsoft/applicationinsights/appsample/ItemListFragment.java#L82-L86).

**Comment by ElektrojungeAtWork** [comment]
Fixed in #49
